<a href="https://colab.research.google.com/github/bhumikaa2060/Machine-Learning/blob/main/01%20Intoduction_to_Machine_Learning/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy
What will we cover?
-creating arrays
-multi dimensional array
-randomly generated arrays
-element wise operators
--comperator operations
--logical operators
--summarizing operations

In [3]:
import numpy as np

##Single dimensional arrays

In [5]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [20]:
 a = np.array([1, 2, 3, 4])
 a[2]= 6
 print(a)

[1 2 6 4]


In [21]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

##Multidimensional arrays

Create arrays with evenly spaced numbers within a specifies range

In [25]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
#create a md unit array size (5,2)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
#Generate random array of size(3,5)
n = np.array([
    [1, 2, 3, 5, 6],
    [2, 5, 7, 3, 6],
    [3, 7, 9, 0, 1]
])
n


array([[1, 2, 3, 5, 6],
       [2, 5, 7, 3, 6],
       [3, 7, 9, 0, 1]])

In [44]:
# update elemnt of an array with index
n[0,1] = 0
n


array([[1, 0, 3, 5, 6],
       [2, 5, 7, 3, 6],
       [3, 7, 9, 0, 1]])

In [45]:
#change last row to 1
n[2]= [1, 1, 1, 1, 1]
n

array([[1, 0, 3, 5, 6],
       [2, 5, 7, 3, 6],
       [1, 1, 1, 1, 1]])

In [46]:
#change last column to 2
n[:, 4] = [2, 2, 2]
n

array([[1, 0, 3, 5, 2],
       [2, 5, 7, 3, 2],
       [1, 1, 1, 1, 2]])

##Randomly generated arrays
-NumPy can create arrays filled with random numbers.
-To ensure the reproducibility, you can set a seed using np.random.seed()
-Everytime you run the code with np.random.seed(2), it will generate the exact same randum numbers.
If you remove or change the seed values, the sequence of random numbers will be changed.

In [59]:
np.random.rand(5)

array([0.81066246, 0.88334956, 0.29068189, 0.55050825, 0.37776195])

In [75]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [84]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [89]:
np.random.randn(5, 2)

array([[-0.33633626, -0.10061435],
       [ 1.41339802,  0.22125412],
       [-1.31077313, -0.68956523],
       [-0.57751323,  1.15220477],
       [-0.10716398,  2.26010677]])

In [94]:
np.random.seed(42)
np.random.randint(low= 0, high= 100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

##Elementwise operations

In [97]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [98]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [99]:
#Comparision operations
#You can perform element wise comparisions and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [101]:
a >= 2

array([False, False,  True,  True,  True])

In [103]:
a > b

array([False, False, False, False, False])

In [104]:
#Summarizing
#Numpy provides functions for summarizing array of data
a


array([0, 1, 2, 3, 4])

In [105]:
#standard deviation
a.std()

1.4142135623730951

In [106]:
#minimum value of array
a.min()

0

In [107]:
#max value of array
a.max()

4

In [108]:
#sum of the elemnets in the array
a.sum()

10